# Generated by Django 2.2.6 on 2019-10-24 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='board',
            field=models.CharField(choices=[('all', 'All'), ('hot', 'Hot')], default='all', max_length=10),
        ),
    ]
