matrix:
  include:
    - language: node_js
      node_js:
        - "10"
      before_install:
        - cd frontend
      install:
        - yarn install
      script:
        - ./node_modules/.bin/eslint src
        - yarn test --coverage --watchAll=false
